# Generated by Django 4.2.3 on 2023-07-28 00:44

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tguser_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Familiya')),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Tg foydalanuvchi nomi')),
                ('phone', models.CharField(max_length=14, unique=True, validators=[config.validators.PhoneValidator])),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Man', 'Man')], default=None, max_length=255, null=True, verbose_name='Jinsi')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('first_post', models.CharField(max_length=255)),
                ('photo', models.ImageField(default='vatanparvar_logo.png', upload_to='Group/', verbose_name='gruppa rasmi')),
                ('users', models.ManyToManyField(to='telegrambot.telegramuser')),
            ],
            options={
                'verbose_name': 'Gruppa',
                'verbose_name_plural': 'Gruppalar',
            },
        ),
    ]
