# Generated by Django 4.2.3 on 2023-07-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.AddField(
            model_name='group',
            name='chat_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
