# Generated by Django 4.2.3 on 2023-07-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_remove_group_description_group_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
